### ISSUE TITLE
Gnome 3.20 : Invalid extension

### ISSUE THREAD

**Issue by tcitworld** [subgraph/gnome-shell-extension-torstatus#13]
Using Arch & Gnome 3.20 :
- pulling last changes
- building
- importing zip file
- Notification : Invalid extension

**Comment by xSmurf** [comment]
Hello @tcitworld, can you try bumping the version in `metadata.json` and report back if everything works properly?

**Comment by tcitworld** [comment]
Unfortunately it doesn't work.

**Comment by xSmurf** [comment]
What seems to be the problem after bumping the version? Is there any error output in syslog?

**Comment by tcitworld** [comment]
```
WARNING : Error parsing theme zip
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 250, in _on_file_set
     verb = _("%s extension installed successfully") % extension_uuid
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```

**Comment by xSmurf** [comment]
This error doesn't seem related to this extension. After bumping the metadata.json did you refresh the gnome-shell session and relaunch tweak tools?

**Comment by xSmurf** [comment]
The extension works fine in 3.20 under stretch with a bumped metadata file, I'm closing this. Feel free to reopen if you have more details
