### ISSUE TITLE
"recipe for target 'src/schemas/gschemas.compiled' failed" while building

### ISSUE THREAD

**Issue by sajolida** [subgraph/gnome-shell-extension-torstatus#7]
Hi,

I wanted to try your extension from Tails. `./autogen.sh` went OK, so did `./configure --prefix=/usr` but I got the following error while doing `make`:

```
Making all in po
make[1]: Entering directory '/home/amnesia/Persistent/gnome-shell-extension-torstatus/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/amnesia/Persistent/gnome-shell-extension-torstatus/po'
make[1]: Entering directory '/home/amnesia/Persistent/gnome-shell-extension-torstatus'
src/schemas/
/bin/bash: src/schemas/: Is a directory
Makefile:881: recipe for target 'src/schemas/gschemas.compiled' failed
make[1]: *** [src/schemas/gschemas.compiled] Error 126
make[1]: Leaving directory '/home/amnesia/Persistent/gnome-shell-extension-torstatus'
Makefile:440: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by xSmurf** [comment]
Odd I have a different error, a warning in fact, which is simply ignored. The schema isn't used right now so it's not a huge problem. However since it's a stopper for you I've fixed up the schema and it should compile properly now. Can you try 0d62cce?

**Comment by xSmurf** [comment]
@sajolida I've not had a return from you in over a month so I am closing the ticket. If this is still a problem please feel free to reopen :)
